# Generated by Django 4.2.16 on 2024-09-19 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('total_attendees', models.IntegerField()),
                ('guest_names', models.CharField(max_length=255)),
                ('main_guests', models.CharField(max_length=255)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('participants_limit', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED_BY_HOD', 'Approved by HOD'), ('REJECTED_BY_HOD', 'Rejected by HOD'), ('APPROVED_BY_PRINCIPAL', 'Approved by Principal'), ('REJECTED_BY_PRINCIPAL', 'Rejected by Principal'), ('COMPLETED', 'Completed')], default='PENDING', max_length=30)),
                ('admin_contact_number', models.CharField(max_length=15)),
                ('admin_email', models.EmailField(max_length=254)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hod_events', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='principal_events', to=settings.AUTH_USER_MODEL)),
                ('registered_students', models.ManyToManyField(blank=True, related_name='registered_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=50)),
                ('decision_at', models.DateTimeField(auto_now_add=True)),
                ('decision_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='events.event')),
            ],
        ),
    ]
