# Generated by Django 4.2.16 on 2024-09-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('HOD', 'HOD'), ('PRINCIPAL', 'Principal'), ('STUDENT', 'Student')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='usn',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
